# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extremalCurve.ui'
#
# Created by: PyQt4 UI code generator 4.12.dev1605051544
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Extremal_Curve(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(423, 571)
        #self.dockWidgetContents = QtGui.QWidget()
        #self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(DockWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton = QtGui.QPushButton(DockWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 2)
        self.tabWidget = QtGui.QTabWidget(DockWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        #self.label = QtGui.QLabel(self.tab)
        #self.label.setObjectName(_fromUtf8("label"))
        #self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        #self.lineEdit = QtGui.QLineEdit(self.tab)
        #self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        #self.gridLayout_2.addWidget(self.lineEdit, 1, 1, 1, 1)
        #self.label_2 = QtGui.QLabel(self.tab)
        #self.label_2.setObjectName(_fromUtf8("label_2"))
        #self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        #self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        #self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        #self.gridLayout_2.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        #self.label_3 = QtGui.QLabel(self.tab)
        #self.label_3.setObjectName(_fromUtf8("label_3"))
        #self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        #self.lineEdit_3 = QtGui.QLineEdit(self.tab)
        #self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        #self.gridLayout_2.addWidget(self.lineEdit_3, 3, 1, 1, 1)
        #self.label_4 = QtGui.QLabel(self.tab)
        #self.label_4.setObjectName(_fromUtf8("label_4"))
        #self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        #self.lineEdit_4 = QtGui.QLineEdit(self.tab)
        #self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        #self.gridLayout_2.addWidget(self.lineEdit_4, 4, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout_2.addWidget(self.doubleSpinBox, 5, 1, 1, 1)
        #self.label_6 = QtGui.QLabel(self.tab)
        #self.label_6.setObjectName(_fromUtf8("label_6"))
        #self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 7, 0, 1, 1)
        #self.pushButton_3 = QtGui.QPushButton(self.tab)
        #self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        #self.gridLayout_2.addWidget(self.pushButton_3, 2, 1, 1, 1)
        #self.pushButton_4 = QtGui.QPushButton(self.tab)
        #self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        #self.gridLayout_2.addWidget(self.pushButton_4, 3, 1, 1, 1)
        #self.lineEdit_5 = QtGui.QLineEdit(self.tab)
        #self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        #self.gridLayout_2.addWidget(self.lineEdit_5, 0, 1, 1, 1)
        #self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.tab)
        #self.doubleSpinBox_2.setSingleStep(0.01)
        #self.doubleSpinBox_2.setProperty("value", 50.0)
        #self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        #self.gridLayout_2.addWidget(self.doubleSpinBox_2, 6, 1, 1, 1)
        
        self.spinBox = QtGui.QSpinBox(self.tab)
        self.spinBox.setProperty("value", 2)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_2.addWidget(self.spinBox, 0, 1, 1, 1)

        #self.checkBox_5 = QtGui.QCheckBox(self.tab)
        #self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        #self.gridLayout_2.addWidget(self.checkBox_5, 3, 0, 1, 1)

        #self.checkBox_6 = QtGui.QCheckBox(self.tab)
        #self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        #self.gridLayout_2.addWidget(self.checkBox_6, 4, 0, 1, 1)

        #self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.tab)
        #self.doubleSpinBox_2.setMaximum(2.00)
        #self.doubleSpinBox_2.setSingleStep(0.01)
        #self.doubleSpinBox_2.setProperty("value", 0.50)
        #self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        #self.gridLayout_2.addWidget(self.doubleSpinBox_2, 6, 1, 1, 1)

        #self.label = QtGui.QLabel(self.tab)
        #self.label.setObjectName(_fromUtf8("label"))
        #self.gridLayout_2.addWidget(self.label, 6, 0, 1, 1)

        #self.label_3 = QtGui.QLabel(self.tab)
        #self.label_3.setObjectName(_fromUtf8("label_3"))
        #self.gridLayout_2.addWidget(self.label_3, 8, 0, 1, 1)

        #self.horizontalSlider_7 = QtGui.QSlider(self.tab)
        #self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        #self.horizontalSlider_7.setObjectName(_fromUtf8("horizontalSlider_7"))
        #self.horizontalSlider_7.setMaximum(100)
        #self.horizontalSlider_7.setMinimum(0)
        #self.horizontalSlider_7.setValue(10)
        #self.horizontalSlider_7.setSingleStep(1)
        #self.horizontalSlider_7.setTickInterval(100)
        #self.gridLayout_2.addWidget(self.horizontalSlider_7, 8, 1, 1, 2)
       # self.label_4 = QtGui.QLabel(self.tab)
        #self.label_4.setObjectName(_fromUtf8("label_4"))
        #self.gridLayout_2.addWidget(self.label_4, 9, 0, 1, 1)
        #self.spinBox_2 = QtGui.QSpinBox(self.tab)
        #self.spinBox_2.setProperty("value", 8)
        #self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        #self.gridLayout_2.addWidget(self.spinBox_2, 9, 1, 1, 1)

        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkBox_22 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_22.setObjectName(_fromUtf8("checkBox_22"))
        self.gridLayout_3.addWidget(self.checkBox_22, 0, 0, 1, 1)
        self.checkBox_24 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_24.setObjectName(_fromUtf8("checkBox_24"))
        self.gridLayout_3.addWidget(self.checkBox_24, 0, 1, 1, 1)
        self.checkBox_23 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_23.setObjectName(_fromUtf8("checkBox_23"))
        self.gridLayout_3.addWidget(self.checkBox_23, 1, 0, 1, 1)
        self.checkBox_25 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_25.setObjectName(_fromUtf8("checkBox_25"))
        self.gridLayout_3.addWidget(self.checkBox_25, 2, 0, 1, 1)
        self.checkBox_26 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_26.setObjectName(_fromUtf8("checkBox_26"))
        self.gridLayout_3.addWidget(self.checkBox_26, 2, 1, 1, 1)
        self.checkBox_21 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.gridLayout_3.addWidget(self.checkBox_21, 3, 1, 1, 1)
        self.checkBox_27 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_27.setObjectName(_fromUtf8("checkBox_27"))
        self.gridLayout_3.addWidget(self.checkBox_27, 3, 0, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout_3.addWidget(self.checkBox_4, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalSlider_2 = QtGui.QSlider(self.tab_5)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setMinimum(0)
        self.horizontalSlider_2.setValue(50)
        self.horizontalSlider_2.setSingleStep(1)
        self.horizontalSlider_2.setTickInterval(100)
        self.gridLayout_4.addWidget(self.horizontalSlider_2, 2, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_5)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_4.addWidget(self.label_14, 1, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_5)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_4.addWidget(self.checkBox_3, 7, 0, 1, 2)
        self.horizontalSlider_3 = QtGui.QSlider(self.tab_5)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName(_fromUtf8("horizontalSlider_3"))
        self.horizontalSlider_3.setMaximum(100)
        self.horizontalSlider_3.setMinimum(0)
        self.horizontalSlider_3.setValue(50)
        self.horizontalSlider_3.setSingleStep(1)
        self.horizontalSlider_3.setTickInterval(100)
        self.gridLayout_4.addWidget(self.horizontalSlider_3, 2, 3, 1, 1)
        self.horizontalSlider_5 = QtGui.QSlider(self.tab_5)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName(_fromUtf8("horizontalSlider_5"))
        self.horizontalSlider_5.setMaximum(100)
        self.horizontalSlider_5.setMinimum(0)
        self.horizontalSlider_5.setValue(50)
        self.horizontalSlider_5.setSingleStep(1)
        self.horizontalSlider_5.setTickInterval(100)
        self.gridLayout_4.addWidget(self.horizontalSlider_5, 7, 2, 1, 2)
        self.checkBox = QtGui.QCheckBox(self.tab_5)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_4.addWidget(self.checkBox, 0, 0, 1, 2)
        self.checkBox_2 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_4.addWidget(self.checkBox_2, 3, 0, 1, 2)
        self.label_15 = QtGui.QLabel(self.tab_5)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_4.addWidget(self.label_15, 1, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 4, 0, 1, 1)
        self.horizontalSlider = QtGui.QSlider(self.tab_5)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setMinimum(0)
        self.horizontalSlider.setValue(50)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setTickInterval(100)
        self.gridLayout_4.addWidget(self.horizontalSlider, 2, 0, 1, 1)
        self.horizontalSlider_4 = QtGui.QSlider(self.tab_5)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName(_fromUtf8("horizontalSlider_4"))
        self.horizontalSlider_4.setMaximum(100)
        self.horizontalSlider_4.setMinimum(0)
        self.horizontalSlider_4.setValue(50)
        self.horizontalSlider_4.setSingleStep(1)
        self.horizontalSlider_4.setTickInterval(100)
        self.gridLayout_4.addWidget(self.horizontalSlider_4, 4, 1, 1, 3)
        self.horizontalSlider_6 = QtGui.QSlider(self.tab_5)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName(_fromUtf8("horizontalSlider_6"))
        self.horizontalSlider_6.setMaximum(100)
        self.horizontalSlider_6.setMinimum(0)
        self.horizontalSlider_6.setValue(50)
        self.horizontalSlider_6.setSingleStep(1)
        self.horizontalSlider_6.setTickInterval(100)
        self.gridLayout_4.addWidget(self.horizontalSlider_6, 5, 1, 1, 3)
        self.label_8 = QtGui.QLabel(self.tab_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 5, 0, 1, 1)

        self.checkBox_7 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.gridLayout_4.addWidget(self.checkBox_7, 8, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 8, 2, 1, 1)

        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.tab_5)
        self.doubleSpinBox_3.setMaximum(1000000.0)
        self.doubleSpinBox_3.setSingleStep(0.1)
        self.doubleSpinBox_3.setProperty("value", 1.0)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_3, 8, 3, 1, 1)

        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))

        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pushButton_5 = QtGui.QPushButton(self.tab_3)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_5.addWidget(self.pushButton_5, 0, 0, 1, 2)
        self.checkBox_8 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.gridLayout_5.addWidget(self.checkBox_8, 1, 0, 1, 1)
        self.checkBox_9 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.gridLayout_5.addWidget(self.checkBox_9, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 2, 0, 1, 1)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_4.setMaximum(10.00)
        self.doubleSpinBox_4.setSingleStep(0.01)
        self.doubleSpinBox_4.setProperty("value", 1.3)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))

        self.gridLayout_5.addWidget(self.doubleSpinBox_4, 2, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 3, 0, 1, 1)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_5.setSingleStep(0.1)
        self.doubleSpinBox_5.setProperty("value", 10.0)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_5, 3, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 4, 0, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(self.tab_3)
        self.spinBox_3.setProperty("value", 8)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.gridLayout_5.addWidget(self.spinBox_3, 4, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_3)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 5, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_3)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_5.addWidget(self.label_16, 5, 1, 1, 1)
        self.horizontalSlider_8 = QtGui.QSlider(self.tab_3)
        self.horizontalSlider_8.setMaximumSize(QtCore.QSize(16777215, 22))
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setObjectName(_fromUtf8("horizontalSlider_8"))
        self.horizontalSlider_8.setMaximum(100)
        self.horizontalSlider_8.setMinimum(0)
        self.horizontalSlider_8.setValue(10)
        self.horizontalSlider_8.setSingleStep(1)
        self.horizontalSlider_8.setTickInterval(100)

        self.gridLayout_5.addWidget(self.horizontalSlider_8, 6, 0, 1, 1)
        self.horizontalSlider_9 = QtGui.QSlider(self.tab_3)
        self.horizontalSlider_9.setMaximumSize(QtCore.QSize(16777215, 22))
        self.horizontalSlider_9.setProperty("value", 99)
        self.horizontalSlider_9.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_9.setObjectName(_fromUtf8("horizontalSlider_9"))
        self.gridLayout_5.addWidget(self.horizontalSlider_9, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        #DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget", None))
        self.pushButton.setText(_translate("DockWidget", "Run Extremal Curve", None))
        #self.label.setText(_translate("DockWidget", "Width", None))
        #self.lineEdit.setText(_translate("DockWidget", "256", None))
        #self.label_2.setText(_translate("DockWidget", "Height", None))
        #self.lineEdit_2.setText(_translate("DockWidget", "256", None))
        #self.label_3.setText(_translate("DockWidget", "Slices", None))
        #self.lineEdit_3.setText(_translate("DockWidget", "50", None))
        #self.label_4.setText(_translate("DockWidget", "Grid Resolution", None))
        #self.lineEdit_4.setText(_translate("DockWidget", "40", None))
        #self.label.setText(_translate("DockWidget", "Helix distance threshold", None))
        #self.label_3.setText(_translate("DockWidget", "Coil Height Threshold", None))
        self.label_5.setText(_translate("DockWidget", "Slices Thickness", None))
        #self.label_6.setText(_translate("DockWidget", "Isovalue", None))
        self.label_9.setText(_translate("DockWidget", "Kernel Size", None))
        self.pushButton_2.setText(_translate("DockWidget", "Load Skeleton", None))
        #self.pushButton_3.setText(_translate("DockWidget", "Find Helices", None))
        self.pushButton_5.setText(_translate("DockWidget", "Find Helices", None))

        #self.label_4.setText(_translate("DockWidget", "Consecutive Segments", None))
        #self.pushButton_4.setText(_translate("DockWidget", "Max Curve Helices", None))
        #self.checkBox_5.setText(_translate("DockWidget", "Display Helices", None))
        #self.checkBox_6.setText(_translate("DockWidget", "Display Helix Segments", None))
        #self.lineEdit_5.setText(_translate("DockWidget", "2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DockWidget", "Load", None))
        self.checkBox_22.setText(_translate("DockWidget", "Max Curve", None))
        self.checkBox_24.setText(_translate("DockWidget", "Min Curve", None))
        self.checkBox_23.setText(_translate("DockWidget", "Saddle Curve", None))
        self.checkBox_25.setText(_translate("DockWidget", "Min Surface", None))
        self.checkBox_26.setText(_translate("DockWidget", "Max Surface", None))
        self.checkBox_21.setText(_translate("DockWidget", "Min Point", None))
        self.checkBox_27.setText(_translate("DockWidget", "Max Point", None))
        self.checkBox_8.setText(_translate("DockWidget", "Display Helices", None))
        self.checkBox_4.setText(_translate("DockWidget", "Saddle Point", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DockWidget", "Result", None))
        self.label_14.setText(_translate("DockWidget", "Curve:", None))
        self.label_13.setText(_translate("DockWidget", "Point:", None))
        self.checkBox_3.setText(_translate("DockWidget", "Eigenvalue", None))
        self.checkBox.setText(_translate("DockWidget", "Saliency Ratio", None))
        self.checkBox_2.setText(_translate("DockWidget", "Local Intensity", None))
        self.label_15.setText(_translate("DockWidget", "Surface:", None))
        self.label_7.setText(_translate("DockWidget", "Min Geometries", None))
        self.label_8.setText(_translate("DockWidget", "Max Geometries", None))

        self.checkBox_9.setText(_translate("DockWidget", "Display Helix Segments", None))
        self.label_6.setText(_translate("DockWidget", "Helix distance threshold", None))
        self.label_10.setText(_translate("DockWidget", "Coil height threshold", None))
        self.label_11.setText(_translate("DockWidget", "Consecutive Segments", None))
        self.label_12.setText(_translate("DockWidget", "Orthogonal Distance Min", None))
        self.label_16.setText(_translate("DockWidget", "Orthogonal Distance Max", None))

        self.checkBox_7.setText(_translate("DockWidget", "Display Ellipsoids", None))
        self.label_2.setText(_translate("DockWidget", "Ellipsoid Scale", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("DockWidget", "Display", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("DockWidget", "Helix", None))

