# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog_calpha_flexible_fitting.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogCAlphaFlexibleFitting(object):
    def setupUi(self, DialogCAlphaFlexibleFitting):
        DialogCAlphaFlexibleFitting.setObjectName(_fromUtf8("DialogCAlphaFlexibleFitting"))
        DialogCAlphaFlexibleFitting.resize(651, 1079)
        self.verticalLayout = QtGui.QVBoxLayout(DialogCAlphaFlexibleFitting)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(DialogCAlphaFlexibleFitting)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabLoadFiles = QtGui.QWidget()
        self.tabLoadFiles.setEnabled(False)
        self.tabLoadFiles.setObjectName(_fromUtf8("tabLoadFiles"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabLoadFiles)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButtonLoadFilesCAlphaAtoms = QtGui.QPushButton(self.tabLoadFiles)
        self.pushButtonLoadFilesCAlphaAtoms.setObjectName(_fromUtf8("pushButtonLoadFilesCAlphaAtoms"))
        self.verticalLayout_2.addWidget(self.pushButtonLoadFilesCAlphaAtoms)
        self.pushButtonLoadFilesHelixAnnotations = QtGui.QPushButton(self.tabLoadFiles)
        self.pushButtonLoadFilesHelixAnnotations.setObjectName(_fromUtf8("pushButtonLoadFilesHelixAnnotations"))
        self.verticalLayout_2.addWidget(self.pushButtonLoadFilesHelixAnnotations)
        self.pushButtonLoadFilesSkeleton = QtGui.QPushButton(self.tabLoadFiles)
        self.pushButtonLoadFilesSkeleton.setObjectName(_fromUtf8("pushButtonLoadFilesSkeleton"))
        self.verticalLayout_2.addWidget(self.pushButtonLoadFilesSkeleton)
        self.pushButtonLoadCorrespondence = QtGui.QPushButton(self.tabLoadFiles)
        self.pushButtonLoadCorrespondence.setObjectName(_fromUtf8("pushButtonLoadCorrespondence"))
        self.verticalLayout_2.addWidget(self.pushButtonLoadCorrespondence)
        self.tabWidget.addTab(self.tabLoadFiles, _fromUtf8(""))
        self.tabCorrespondenceOptions = QtGui.QWidget()
        self.tabCorrespondenceOptions.setEnabled(False)
        self.tabCorrespondenceOptions.setObjectName(_fromUtf8("tabCorrespondenceOptions"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabCorrespondenceOptions)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayoutCorrespondenceOptions = QtGui.QFormLayout()
        self.formLayoutCorrespondenceOptions.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayoutCorrespondenceOptions.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayoutCorrespondenceOptions.setObjectName(_fromUtf8("formLayoutCorrespondenceOptions"))
        self.labelMaximumAlignments = QtGui.QLabel(self.tabCorrespondenceOptions)
        self.labelMaximumAlignments.setObjectName(_fromUtf8("labelMaximumAlignments"))
        self.formLayoutCorrespondenceOptions.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelMaximumAlignments)
        self.spinBoxMaximumAlignments = QtGui.QSpinBox(self.tabCorrespondenceOptions)
        self.spinBoxMaximumAlignments.setMinimum(1)
        self.spinBoxMaximumAlignments.setMaximum(100)
        self.spinBoxMaximumAlignments.setProperty("value", 5)
        self.spinBoxMaximumAlignments.setObjectName(_fromUtf8("spinBoxMaximumAlignments"))
        self.formLayoutCorrespondenceOptions.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBoxMaximumAlignments)
        self.labelHelixCentroidDifference = QtGui.QLabel(self.tabCorrespondenceOptions)
        self.labelHelixCentroidDifference.setObjectName(_fromUtf8("labelHelixCentroidDifference"))
        self.formLayoutCorrespondenceOptions.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelHelixCentroidDifference)
        self.labelHelixLengthDifference = QtGui.QLabel(self.tabCorrespondenceOptions)
        self.labelHelixLengthDifference.setObjectName(_fromUtf8("labelHelixLengthDifference"))
        self.formLayoutCorrespondenceOptions.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelHelixLengthDifference)
        self.spinBoxHelixLengthDifference = QtGui.QSpinBox(self.tabCorrespondenceOptions)
        self.spinBoxHelixLengthDifference.setMaximum(50)
        self.spinBoxHelixLengthDifference.setProperty("value", 5)
        self.spinBoxHelixLengthDifference.setObjectName(_fromUtf8("spinBoxHelixLengthDifference"))
        self.formLayoutCorrespondenceOptions.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinBoxHelixLengthDifference)
        self.spinBoxHelixCentroidDifference = QtGui.QSpinBox(self.tabCorrespondenceOptions)
        self.spinBoxHelixCentroidDifference.setMaximum(50)
        self.spinBoxHelixCentroidDifference.setProperty("value", 5)
        self.spinBoxHelixCentroidDifference.setObjectName(_fromUtf8("spinBoxHelixCentroidDifference"))
        self.formLayoutCorrespondenceOptions.setWidget(3, QtGui.QFormLayout.FieldRole, self.spinBoxHelixCentroidDifference)
        self.labelJoinAngleDifference = QtGui.QLabel(self.tabCorrespondenceOptions)
        self.labelJoinAngleDifference.setObjectName(_fromUtf8("labelJoinAngleDifference"))
        self.formLayoutCorrespondenceOptions.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelJoinAngleDifference)
        self.spinBoxJointAngleDifference = QtGui.QSpinBox(self.tabCorrespondenceOptions)
        self.spinBoxJointAngleDifference.setMaximum(180)
        self.spinBoxJointAngleDifference.setProperty("value", 30)
        self.spinBoxJointAngleDifference.setObjectName(_fromUtf8("spinBoxJointAngleDifference"))
        self.formLayoutCorrespondenceOptions.setWidget(4, QtGui.QFormLayout.FieldRole, self.spinBoxJointAngleDifference)
        self.labelDihedralAngleDifference = QtGui.QLabel(self.tabCorrespondenceOptions)
        self.labelDihedralAngleDifference.setObjectName(_fromUtf8("labelDihedralAngleDifference"))
        self.formLayoutCorrespondenceOptions.setWidget(5, QtGui.QFormLayout.LabelRole, self.labelDihedralAngleDifference)
        self.spinBoxDihedralAngleDifference = QtGui.QSpinBox(self.tabCorrespondenceOptions)
        self.spinBoxDihedralAngleDifference.setMaximum(180)
        self.spinBoxDihedralAngleDifference.setProperty("value", 30)
        self.spinBoxDihedralAngleDifference.setObjectName(_fromUtf8("spinBoxDihedralAngleDifference"))
        self.formLayoutCorrespondenceOptions.setWidget(5, QtGui.QFormLayout.FieldRole, self.spinBoxDihedralAngleDifference)
        self.verticalLayout_3.addLayout(self.formLayoutCorrespondenceOptions)
        self.horizontalLayoutCorrespondenceOptions = QtGui.QHBoxLayout()
        self.horizontalLayoutCorrespondenceOptions.setObjectName(_fromUtf8("horizontalLayoutCorrespondenceOptions"))
        self.pushButtonCorrespondenceOptionsCalculate = QtGui.QPushButton(self.tabCorrespondenceOptions)
        self.pushButtonCorrespondenceOptionsCalculate.setObjectName(_fromUtf8("pushButtonCorrespondenceOptionsCalculate"))
        self.horizontalLayoutCorrespondenceOptions.addWidget(self.pushButtonCorrespondenceOptionsCalculate)
        self.verticalLayout_3.addLayout(self.horizontalLayoutCorrespondenceOptions)
        self.tabWidget.addTab(self.tabCorrespondenceOptions, _fromUtf8(""))
        self.tabCorrespondences = QtGui.QWidget()
        self.tabCorrespondences.setEnabled(False)
        self.tabCorrespondences.setObjectName(_fromUtf8("tabCorrespondences"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabCorrespondences)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.formLayoutCorrespodences = QtGui.QFormLayout()
        self.formLayoutCorrespodences.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayoutCorrespodences.setObjectName(_fromUtf8("formLayoutCorrespodences"))
        self.comboBoxAlignment = QtGui.QComboBox(self.tabCorrespondences)
        self.comboBoxAlignment.setObjectName(_fromUtf8("comboBoxAlignment"))
        self.formLayoutCorrespodences.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxAlignment)
        self.labelAlignment = QtGui.QLabel(self.tabCorrespondences)
        self.labelAlignment.setObjectName(_fromUtf8("labelAlignment"))
        self.formLayoutCorrespodences.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelAlignment)
        self.verticalLayout_4.addLayout(self.formLayoutCorrespodences)
        self.tableWidgetCorrespondences = QtGui.QTableWidget(self.tabCorrespondences)
        self.tableWidgetCorrespondences.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidgetCorrespondences.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidgetCorrespondences.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetCorrespondences.setObjectName(_fromUtf8("tableWidgetCorrespondences"))
        self.tableWidgetCorrespondences.setColumnCount(4)
        self.tableWidgetCorrespondences.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidgetCorrespondences.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidgetCorrespondences.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidgetCorrespondences.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidgetCorrespondences.setHorizontalHeaderItem(3, item)
        self.tableWidgetCorrespondences.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetCorrespondences.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetCorrespondences.verticalHeader().setDefaultSectionSize(20)
        self.tableWidgetCorrespondences.verticalHeader().setMinimumSectionSize(20)
        self.tableWidgetCorrespondences.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.tableWidgetCorrespondences)
        self.lineAlignToCluster = QtGui.QFrame(self.tabCorrespondences)
        self.lineAlignToCluster.setFrameShape(QtGui.QFrame.HLine)
        self.lineAlignToCluster.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineAlignToCluster.setObjectName(_fromUtf8("lineAlignToCluster"))
        self.verticalLayout_4.addWidget(self.lineAlignToCluster)
        self.formAlignToCluster = QtGui.QGroupBox(self.tabCorrespondences)
        self.formAlignToCluster.setObjectName(_fromUtf8("formAlignToCluster"))
        self.formLayout_5 = QtGui.QFormLayout(self.formAlignToCluster)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.labelCluster = QtGui.QLabel(self.formAlignToCluster)
        self.labelCluster.setObjectName(_fromUtf8("labelCluster"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelCluster)
        self.comboBoxCluster = QtGui.QComboBox(self.formAlignToCluster)
        self.comboBoxCluster.setObjectName(_fromUtf8("comboBoxCluster"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxCluster)
        self.pushButtonCorrespondencesAlignToCluster = QtGui.QPushButton(self.formAlignToCluster)
        self.pushButtonCorrespondencesAlignToCluster.setCheckable(True)
        self.pushButtonCorrespondencesAlignToCluster.setObjectName(_fromUtf8("pushButtonCorrespondencesAlignToCluster"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.pushButtonCorrespondencesAlignToCluster)
        self.verticalLayout_4.addWidget(self.formAlignToCluster)
        self.lineMergeClusters = QtGui.QFrame(self.tabCorrespondences)
        self.lineMergeClusters.setFrameShape(QtGui.QFrame.HLine)
        self.lineMergeClusters.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineMergeClusters.setObjectName(_fromUtf8("lineMergeClusters"))
        self.verticalLayout_4.addWidget(self.lineMergeClusters)
        self.formMergeClusters = QtGui.QGroupBox(self.tabCorrespondences)
        self.formMergeClusters.setObjectName(_fromUtf8("formMergeClusters"))
        self.formLayout = QtGui.QFormLayout(self.formMergeClusters)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelFirstCluster = QtGui.QLabel(self.formMergeClusters)
        self.labelFirstCluster.setObjectName(_fromUtf8("labelFirstCluster"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelFirstCluster)
        self.comboBoxFirstCluster = QtGui.QComboBox(self.formMergeClusters)
        self.comboBoxFirstCluster.setObjectName(_fromUtf8("comboBoxFirstCluster"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBoxFirstCluster)
        self.labelSecondCluster = QtGui.QLabel(self.formMergeClusters)
        self.labelSecondCluster.setObjectName(_fromUtf8("labelSecondCluster"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelSecondCluster)
        self.comboBoxSecondCluster = QtGui.QComboBox(self.formMergeClusters)
        self.comboBoxSecondCluster.setObjectName(_fromUtf8("comboBoxSecondCluster"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBoxSecondCluster)
        self.pushButtonCorrespondencesMerge = QtGui.QPushButton(self.formMergeClusters)
        self.pushButtonCorrespondencesMerge.setObjectName(_fromUtf8("pushButtonCorrespondencesMerge"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.pushButtonCorrespondencesMerge)
        self.verticalLayout_4.addWidget(self.formMergeClusters)
        self.lineManualCorrespondence = QtGui.QFrame(self.tabCorrespondences)
        self.lineManualCorrespondence.setFrameShape(QtGui.QFrame.HLine)
        self.lineManualCorrespondence.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineManualCorrespondence.setObjectName(_fromUtf8("lineManualCorrespondence"))
        self.verticalLayout_4.addWidget(self.lineManualCorrespondence)
        self.formManualCorresponence = QtGui.QGroupBox(self.tabCorrespondences)
        self.formManualCorresponence.setObjectName(_fromUtf8("formManualCorresponence"))
        self.verticalLayoutCorrespondences = QtGui.QVBoxLayout(self.formManualCorresponence)
        self.verticalLayoutCorrespondences.setObjectName(_fromUtf8("verticalLayoutCorrespondences"))
        self.labelMatch = QtGui.QLabel(self.formManualCorresponence)
        self.labelMatch.setWordWrap(True)
        self.labelMatch.setObjectName(_fromUtf8("labelMatch"))
        self.verticalLayoutCorrespondences.addWidget(self.labelMatch)
        self.pushButtonCorrespondencesManualCorrespondence = QtGui.QPushButton(self.formManualCorresponence)
        self.pushButtonCorrespondencesManualCorrespondence.setObjectName(_fromUtf8("pushButtonCorrespondencesManualCorrespondence"))
        self.verticalLayoutCorrespondences.addWidget(self.pushButtonCorrespondencesManualCorrespondence)
        self.verticalLayout_4.addWidget(self.formManualCorresponence)
        self.lineFlipCorrespondenceDirection = QtGui.QFrame(self.tabCorrespondences)
        self.lineFlipCorrespondenceDirection.setFrameShape(QtGui.QFrame.HLine)
        self.lineFlipCorrespondenceDirection.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineFlipCorrespondenceDirection.setObjectName(_fromUtf8("lineFlipCorrespondenceDirection"))
        self.verticalLayout_4.addWidget(self.lineFlipCorrespondenceDirection)
        self.formFlipCorrespondenceDirection = QtGui.QGroupBox(self.tabCorrespondences)
        self.formFlipCorrespondenceDirection.setObjectName(_fromUtf8("formFlipCorrespondenceDirection"))
        self.formLayout_6 = QtGui.QFormLayout(self.formFlipCorrespondenceDirection)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.labelFlipCorrespondenceDirection = QtGui.QLabel(self.formFlipCorrespondenceDirection)
        self.labelFlipCorrespondenceDirection.setObjectName(_fromUtf8("labelFlipCorrespondenceDirection"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.SpanningRole, self.labelFlipCorrespondenceDirection)
        self.pushButtonCorrespondencesFlipCorrespondence = QtGui.QPushButton(self.formFlipCorrespondenceDirection)
        self.pushButtonCorrespondencesFlipCorrespondence.setObjectName(_fromUtf8("pushButtonCorrespondencesFlipCorrespondence"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.SpanningRole, self.pushButtonCorrespondencesFlipCorrespondence)
        self.verticalLayout_4.addWidget(self.formFlipCorrespondenceDirection)
        self.linePreviewCorrespondences = QtGui.QFrame(self.tabCorrespondences)
        self.linePreviewCorrespondences.setFrameShape(QtGui.QFrame.HLine)
        self.linePreviewCorrespondences.setFrameShadow(QtGui.QFrame.Sunken)
        self.linePreviewCorrespondences.setObjectName(_fromUtf8("linePreviewCorrespondences"))
        self.verticalLayout_4.addWidget(self.linePreviewCorrespondences)
        self.labelConfirmCorrespondences = QtGui.QLabel(self.tabCorrespondences)
        self.labelConfirmCorrespondences.setObjectName(_fromUtf8("labelConfirmCorrespondences"))
        self.verticalLayout_4.addWidget(self.labelConfirmCorrespondences)
        self.horizontalLayoutCorrespondenceConfirmation = QtGui.QHBoxLayout()
        self.horizontalLayoutCorrespondenceConfirmation.setObjectName(_fromUtf8("horizontalLayoutCorrespondenceConfirmation"))
        self.pushButtonCorrespondencesPreview = QtGui.QPushButton(self.tabCorrespondences)
        self.pushButtonCorrespondencesPreview.setCheckable(True)
        self.pushButtonCorrespondencesPreview.setDefault(False)
        self.pushButtonCorrespondencesPreview.setFlat(False)
        self.pushButtonCorrespondencesPreview.setObjectName(_fromUtf8("pushButtonCorrespondencesPreview"))
        self.horizontalLayoutCorrespondenceConfirmation.addWidget(self.pushButtonCorrespondencesPreview)
        self.pushButtonCorrespondencesReject = QtGui.QPushButton(self.tabCorrespondences)
        self.pushButtonCorrespondencesReject.setObjectName(_fromUtf8("pushButtonCorrespondencesReject"))
        self.horizontalLayoutCorrespondenceConfirmation.addWidget(self.pushButtonCorrespondencesReject)
        self.pushButtonCorrespondencesAccept = QtGui.QPushButton(self.tabCorrespondences)
        self.pushButtonCorrespondencesAccept.setObjectName(_fromUtf8("pushButtonCorrespondencesAccept"))
        self.horizontalLayoutCorrespondenceConfirmation.addWidget(self.pushButtonCorrespondencesAccept)
        self.verticalLayout_4.addLayout(self.horizontalLayoutCorrespondenceConfirmation)
        self.tabWidget.addTab(self.tabCorrespondences, _fromUtf8(""))
        self.tabDeformationOptions = QtGui.QWidget()
        self.tabDeformationOptions.setEnabled(False)
        self.tabDeformationOptions.setObjectName(_fromUtf8("tabDeformationOptions"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabDeformationOptions)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBoxRigidFitting = QtGui.QGroupBox(self.tabDeformationOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxRigidFitting.sizePolicy().hasHeightForWidth())
        self.groupBoxRigidFitting.setSizePolicy(sizePolicy)
        self.groupBoxRigidFitting.setObjectName(_fromUtf8("groupBoxRigidFitting"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxRigidFitting)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButtonDeformationRigidDeform = QtGui.QPushButton(self.groupBoxRigidFitting)
        self.pushButtonDeformationRigidDeform.setObjectName(_fromUtf8("pushButtonDeformationRigidDeform"))
        self.gridLayout_2.addWidget(self.pushButtonDeformationRigidDeform, 2, 0, 1, 1)
        self.groupBoxDeformationRigidGlobalOptions = QtGui.QGroupBox(self.groupBoxRigidFitting)
        self.groupBoxDeformationRigidGlobalOptions.setObjectName(_fromUtf8("groupBoxDeformationRigidGlobalOptions"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBoxDeformationRigidGlobalOptions)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.formLayoutDeformationRigidGlobalOptions = QtGui.QFormLayout()
        self.formLayoutDeformationRigidGlobalOptions.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayoutDeformationRigidGlobalOptions.setObjectName(_fromUtf8("formLayoutDeformationRigidGlobalOptions"))
        self.labelDeformationRigidFittingMatch = QtGui.QLabel(self.groupBoxDeformationRigidGlobalOptions)
        self.labelDeformationRigidFittingMatch.setObjectName(_fromUtf8("labelDeformationRigidFittingMatch"))
        self.formLayoutDeformationRigidGlobalOptions.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelDeformationRigidFittingMatch)
        self.comboBoxDeformationRigidFittingMethod = QtGui.QComboBox(self.groupBoxDeformationRigidGlobalOptions)
        self.comboBoxDeformationRigidFittingMethod.setObjectName(_fromUtf8("comboBoxDeformationRigidFittingMethod"))
        self.comboBoxDeformationRigidFittingMethod.addItem(_fromUtf8(""))
        self.comboBoxDeformationRigidFittingMethod.addItem(_fromUtf8(""))
        self.comboBoxDeformationRigidFittingMethod.addItem(_fromUtf8(""))
        self.formLayoutDeformationRigidGlobalOptions.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxDeformationRigidFittingMethod)
        self.gridLayout_6.addLayout(self.formLayoutDeformationRigidGlobalOptions, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxDeformationRigidGlobalOptions, 0, 0, 1, 1)
        self.groupBoxRigidDeformationPrincipalComponentMatching = QtGui.QGroupBox(self.groupBoxRigidFitting)
        self.groupBoxRigidDeformationPrincipalComponentMatching.setObjectName(_fromUtf8("groupBoxRigidDeformationPrincipalComponentMatching"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxRigidDeformationPrincipalComponentMatching)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.formLayoutRigidDeformationPrincipalComponentMatchingOptions = QtGui.QFormLayout()
        self.formLayoutRigidDeformationPrincipalComponentMatchingOptions.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayoutRigidDeformationPrincipalComponentMatchingOptions.setContentsMargins(-1, -1, 0, -1)
        self.formLayoutRigidDeformationPrincipalComponentMatchingOptions.setObjectName(_fromUtf8("formLayoutRigidDeformationPrincipalComponentMatchingOptions"))
        self.labelDeformationRigidPrincipalComponentOrientation = QtGui.QLabel(self.groupBoxRigidDeformationPrincipalComponentMatching)
        self.labelDeformationRigidPrincipalComponentOrientation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDeformationRigidPrincipalComponentOrientation.setObjectName(_fromUtf8("labelDeformationRigidPrincipalComponentOrientation"))
        self.formLayoutRigidDeformationPrincipalComponentMatchingOptions.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelDeformationRigidPrincipalComponentOrientation)
        self.comboBoxRigidDeformationPrincipalComponentOrientation = QtGui.QComboBox(self.groupBoxRigidDeformationPrincipalComponentMatching)
        self.comboBoxRigidDeformationPrincipalComponentOrientation.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBoxRigidDeformationPrincipalComponentOrientation.setMinimumContentsLength(26)
        self.comboBoxRigidDeformationPrincipalComponentOrientation.setObjectName(_fromUtf8("comboBoxRigidDeformationPrincipalComponentOrientation"))
        self.comboBoxRigidDeformationPrincipalComponentOrientation.addItem(_fromUtf8(""))
        self.comboBoxRigidDeformationPrincipalComponentOrientation.addItem(_fromUtf8(""))
        self.comboBoxRigidDeformationPrincipalComponentOrientation.addItem(_fromUtf8(""))
        self.comboBoxRigidDeformationPrincipalComponentOrientation.addItem(_fromUtf8(""))
        self.comboBoxRigidDeformationPrincipalComponentOrientation.addItem(_fromUtf8(""))
        self.formLayoutRigidDeformationPrincipalComponentMatchingOptions.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxRigidDeformationPrincipalComponentOrientation)
        self.labelDeformationPrincipalComponentTarget = QtGui.QLabel(self.groupBoxRigidDeformationPrincipalComponentMatching)
        self.labelDeformationPrincipalComponentTarget.setObjectName(_fromUtf8("labelDeformationPrincipalComponentTarget"))
        self.formLayoutRigidDeformationPrincipalComponentMatchingOptions.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelDeformationPrincipalComponentTarget)
        self.pushButtonRigidDeformationPrincipalComponentTarget = QtGui.QPushButton(self.groupBoxRigidDeformationPrincipalComponentMatching)
        self.pushButtonRigidDeformationPrincipalComponentTarget.setCheckable(True)
        self.pushButtonRigidDeformationPrincipalComponentTarget.setObjectName(_fromUtf8("pushButtonRigidDeformationPrincipalComponentTarget"))
        self.formLayoutRigidDeformationPrincipalComponentMatchingOptions.setWidget(1, QtGui.QFormLayout.FieldRole, self.pushButtonRigidDeformationPrincipalComponentTarget)
        self.gridLayout_3.addLayout(self.formLayoutRigidDeformationPrincipalComponentMatchingOptions, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxRigidDeformationPrincipalComponentMatching, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBoxRigidFitting)
        self.lineDeformation = QtGui.QFrame(self.tabDeformationOptions)
        self.lineDeformation.setFrameShape(QtGui.QFrame.HLine)
        self.lineDeformation.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineDeformation.setObjectName(_fromUtf8("lineDeformation"))
        self.verticalLayout_5.addWidget(self.lineDeformation)
        self.groupBoxFlexibleFitting = QtGui.QGroupBox(self.tabDeformationOptions)
        self.groupBoxFlexibleFitting.setObjectName(_fromUtf8("groupBoxFlexibleFitting"))
        self.gridLayout = QtGui.QGridLayout(self.groupBoxFlexibleFitting)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBoxFlexibleDeformationGlobalOptions = QtGui.QGroupBox(self.groupBoxFlexibleFitting)
        self.groupBoxFlexibleDeformationGlobalOptions.setObjectName(_fromUtf8("groupBoxFlexibleDeformationGlobalOptions"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBoxFlexibleDeformationGlobalOptions)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelLaplacianNeighborhoodSize = QtGui.QLabel(self.groupBoxFlexibleDeformationGlobalOptions)
        self.labelLaplacianNeighborhoodSize.setObjectName(_fromUtf8("labelLaplacianNeighborhoodSize"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelLaplacianNeighborhoodSize)
        self.spinBoxLaplacianNeighborhoodSize = QtGui.QSpinBox(self.groupBoxFlexibleDeformationGlobalOptions)
        self.spinBoxLaplacianNeighborhoodSize.setProperty("value", 10)
        self.spinBoxLaplacianNeighborhoodSize.setObjectName(_fromUtf8("spinBoxLaplacianNeighborhoodSize"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBoxLaplacianNeighborhoodSize)
        self.labelTransformation = QtGui.QLabel(self.groupBoxFlexibleDeformationGlobalOptions)
        self.labelTransformation.setTextFormat(QtCore.Qt.PlainText)
        self.labelTransformation.setObjectName(_fromUtf8("labelTransformation"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelTransformation)
        self.spinBoxTransformationNeighborhoodSize = QtGui.QSpinBox(self.groupBoxFlexibleDeformationGlobalOptions)
        self.spinBoxTransformationNeighborhoodSize.setProperty("value", 10)
        self.spinBoxTransformationNeighborhoodSize.setObjectName(_fromUtf8("spinBoxTransformationNeighborhoodSize"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBoxTransformationNeighborhoodSize)
        self.gridLayout.addWidget(self.groupBoxFlexibleDeformationGlobalOptions, 0, 0, 1, 1)
        self.groupBoxFlexibleDeformationSkeletonFitting = QtGui.QGroupBox(self.groupBoxFlexibleFitting)
        self.groupBoxFlexibleDeformationSkeletonFitting.setObjectName(_fromUtf8("groupBoxFlexibleDeformationSkeletonFitting"))
        self.formLayout_4 = QtGui.QFormLayout(self.groupBoxFlexibleDeformationSkeletonFitting)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.labelSkeletonFittingIterations = QtGui.QLabel(self.groupBoxFlexibleDeformationSkeletonFitting)
        self.labelSkeletonFittingIterations.setObjectName(_fromUtf8("labelSkeletonFittingIterations"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelSkeletonFittingIterations)
        self.spinBoxSkeletonFittingIterations = QtGui.QSpinBox(self.groupBoxFlexibleDeformationSkeletonFitting)
        self.spinBoxSkeletonFittingIterations.setProperty("value", 10)
        self.spinBoxSkeletonFittingIterations.setObjectName(_fromUtf8("spinBoxSkeletonFittingIterations"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBoxSkeletonFittingIterations)
        self.labelDistanceTreshold = QtGui.QLabel(self.groupBoxFlexibleDeformationSkeletonFitting)
        self.labelDistanceTreshold.setObjectName(_fromUtf8("labelDistanceTreshold"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelDistanceTreshold)
        self.spinBoxSkeletonFittingDistanceThreshold = QtGui.QSpinBox(self.groupBoxFlexibleDeformationSkeletonFitting)
        self.spinBoxSkeletonFittingDistanceThreshold.setMinimum(0)
        self.spinBoxSkeletonFittingDistanceThreshold.setProperty("value", 10)
        self.spinBoxSkeletonFittingDistanceThreshold.setObjectName(_fromUtf8("spinBoxSkeletonFittingDistanceThreshold"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBoxSkeletonFittingDistanceThreshold)
        self.labelSkeletonFittingWeight = QtGui.QLabel(self.groupBoxFlexibleDeformationSkeletonFitting)
        self.labelSkeletonFittingWeight.setObjectName(_fromUtf8("labelSkeletonFittingWeight"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelSkeletonFittingWeight)
        self.doubleSpinBoxSkeletonFittingWeight = QtGui.QDoubleSpinBox(self.groupBoxFlexibleDeformationSkeletonFitting)
        self.doubleSpinBoxSkeletonFittingWeight.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.doubleSpinBoxSkeletonFittingWeight.setMaximum(1.0)
        self.doubleSpinBoxSkeletonFittingWeight.setSingleStep(0.1)
        self.doubleSpinBoxSkeletonFittingWeight.setProperty("value", 0.1)
        self.doubleSpinBoxSkeletonFittingWeight.setObjectName(_fromUtf8("doubleSpinBoxSkeletonFittingWeight"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxSkeletonFittingWeight)
        self.labelSkeletonDistortionWeight = QtGui.QLabel(self.groupBoxFlexibleDeformationSkeletonFitting)
        self.labelSkeletonDistortionWeight.setObjectName(_fromUtf8("labelSkeletonDistortionWeight"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelSkeletonDistortionWeight)
        self.doubleSpinBoxSkeletonDistortionWeight = QtGui.QDoubleSpinBox(self.groupBoxFlexibleDeformationSkeletonFitting)
        self.doubleSpinBoxSkeletonDistortionWeight.setMaximum(1.0)
        self.doubleSpinBoxSkeletonDistortionWeight.setSingleStep(0.1)
        self.doubleSpinBoxSkeletonDistortionWeight.setProperty("value", 1.0)
        self.doubleSpinBoxSkeletonDistortionWeight.setObjectName(_fromUtf8("doubleSpinBoxSkeletonDistortionWeight"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxSkeletonDistortionWeight)
        self.gridLayout.addWidget(self.groupBoxFlexibleDeformationSkeletonFitting, 3, 0, 1, 1)
        self.pushButtonDeformationFlexibleDeform = QtGui.QPushButton(self.groupBoxFlexibleFitting)
        self.pushButtonDeformationFlexibleDeform.setObjectName(_fromUtf8("pushButtonDeformationFlexibleDeform"))
        self.gridLayout.addWidget(self.pushButtonDeformationFlexibleDeform, 4, 0, 1, 1)
        self.groupBoxFlexibleDeformationCorrespondenceFitting = QtGui.QGroupBox(self.groupBoxFlexibleFitting)
        self.groupBoxFlexibleDeformationCorrespondenceFitting.setObjectName(_fromUtf8("groupBoxFlexibleDeformationCorrespondenceFitting"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBoxFlexibleDeformationCorrespondenceFitting)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.labelBoundingBoxRatio = QtGui.QLabel(self.groupBoxFlexibleDeformationCorrespondenceFitting)
        self.labelBoundingBoxRatio.setObjectName(_fromUtf8("labelBoundingBoxRatio"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelBoundingBoxRatio)
        self.doubleSpinBoxBoudingBoxRatio = QtGui.QDoubleSpinBox(self.groupBoxFlexibleDeformationCorrespondenceFitting)
        self.doubleSpinBoxBoudingBoxRatio.setMinimum(0.01)
        self.doubleSpinBoxBoudingBoxRatio.setMaximum(1.0)
        self.doubleSpinBoxBoudingBoxRatio.setSingleStep(0.1)
        self.doubleSpinBoxBoudingBoxRatio.setProperty("value", 0.3)
        self.doubleSpinBoxBoudingBoxRatio.setObjectName(_fromUtf8("doubleSpinBoxBoudingBoxRatio"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBoudingBoxRatio)
        self.checkBoxRigidInitialization = QtGui.QCheckBox(self.groupBoxFlexibleDeformationCorrespondenceFitting)
        self.checkBoxRigidInitialization.setChecked(True)
        self.checkBoxRigidInitialization.setTristate(False)
        self.checkBoxRigidInitialization.setObjectName(_fromUtf8("checkBoxRigidInitialization"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.checkBoxRigidInitialization)
        self.checkBoxWSVD = QtGui.QCheckBox(self.groupBoxFlexibleDeformationCorrespondenceFitting)
        self.checkBoxWSVD.setChecked(True)
        self.checkBoxWSVD.setObjectName(_fromUtf8("checkBoxWSVD"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.checkBoxWSVD)
        self.checkBoxAutoStop = QtGui.QCheckBox(self.groupBoxFlexibleDeformationCorrespondenceFitting)
        self.checkBoxAutoStop.setChecked(True)
        self.checkBoxAutoStop.setObjectName(_fromUtf8("checkBoxAutoStop"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.checkBoxAutoStop)
        self.label = QtGui.QLabel(self.groupBoxFlexibleDeformationCorrespondenceFitting)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.doubleSpinBoxStopThreshold = QtGui.QDoubleSpinBox(self.groupBoxFlexibleDeformationCorrespondenceFitting)
        self.doubleSpinBoxStopThreshold.setMaximum(5.0)
        self.doubleSpinBoxStopThreshold.setProperty("value", 0.1)
        self.doubleSpinBoxStopThreshold.setObjectName(_fromUtf8("doubleSpinBoxStopThreshold"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxStopThreshold)
        self.gridLayout.addWidget(self.groupBoxFlexibleDeformationCorrespondenceFitting, 1, 0, 2, 1)
        self.verticalLayout_5.addWidget(self.groupBoxFlexibleFitting)
        self.tabWidget.addTab(self.tabDeformationOptions, _fromUtf8(""))
        self.tabDeformation = QtGui.QWidget()
        self.tabDeformation.setEnabled(False)
        self.tabDeformation.setObjectName(_fromUtf8("tabDeformation"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabDeformation)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.labelConfirmDeformation = QtGui.QLabel(self.tabDeformation)
        self.labelConfirmDeformation.setObjectName(_fromUtf8("labelConfirmDeformation"))
        self.verticalLayout_6.addWidget(self.labelConfirmDeformation)
        self.horizontalLayoutConfirmDeformation = QtGui.QHBoxLayout()
        self.horizontalLayoutConfirmDeformation.setObjectName(_fromUtf8("horizontalLayoutConfirmDeformation"))
        self.pushButtonDeformationReject = QtGui.QPushButton(self.tabDeformation)
        self.pushButtonDeformationReject.setObjectName(_fromUtf8("pushButtonDeformationReject"))
        self.horizontalLayoutConfirmDeformation.addWidget(self.pushButtonDeformationReject)
        self.pushButtonDeformationAccept = QtGui.QPushButton(self.tabDeformation)
        self.pushButtonDeformationAccept.setObjectName(_fromUtf8("pushButtonDeformationAccept"))
        self.horizontalLayoutConfirmDeformation.addWidget(self.pushButtonDeformationAccept)
        self.verticalLayout_6.addLayout(self.horizontalLayoutConfirmDeformation)
        spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.tabWidget.addTab(self.tabDeformation, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(DialogCAlphaFlexibleFitting)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(DialogCAlphaFlexibleFitting)

    def retranslateUi(self, DialogCAlphaFlexibleFitting):
        DialogCAlphaFlexibleFitting.setWindowTitle(_translate("DialogCAlphaFlexibleFitting", "Dialog", None))
        self.pushButtonLoadFilesCAlphaAtoms.setText(_translate("DialogCAlphaFlexibleFitting", "CAlpha Atoms", None))
        self.pushButtonLoadFilesHelixAnnotations.setText(_translate("DialogCAlphaFlexibleFitting", "Helix Annotations", None))
        self.pushButtonLoadFilesSkeleton.setText(_translate("DialogCAlphaFlexibleFitting", "Skeleton", None))
        self.pushButtonLoadCorrespondence.setText(_translate("DialogCAlphaFlexibleFitting", "Correspondence", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLoadFiles), _translate("DialogCAlphaFlexibleFitting", "Load Files", None))
        self.labelMaximumAlignments.setText(_translate("DialogCAlphaFlexibleFitting", "Maximum Alignments", None))
        self.labelHelixCentroidDifference.setText(_translate("DialogCAlphaFlexibleFitting", "Helix Centroid Difference", None))
        self.labelHelixLengthDifference.setText(_translate("DialogCAlphaFlexibleFitting", "Helix Length Difference", None))
        self.spinBoxHelixLengthDifference.setSuffix(_translate("DialogCAlphaFlexibleFitting", " Å", None))
        self.spinBoxHelixCentroidDifference.setSuffix(_translate("DialogCAlphaFlexibleFitting", " Å", None))
        self.labelJoinAngleDifference.setText(_translate("DialogCAlphaFlexibleFitting", "Joint Angle Difference", None))
        self.spinBoxJointAngleDifference.setSuffix(_translate("DialogCAlphaFlexibleFitting", "°", None))
        self.labelDihedralAngleDifference.setText(_translate("DialogCAlphaFlexibleFitting", "Dihedral Angle Difference", None))
        self.spinBoxDihedralAngleDifference.setSuffix(_translate("DialogCAlphaFlexibleFitting", "°", None))
        self.pushButtonCorrespondenceOptionsCalculate.setText(_translate("DialogCAlphaFlexibleFitting", "Calculate", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCorrespondenceOptions), _translate("DialogCAlphaFlexibleFitting", "Correspondence Options", None))
        self.labelAlignment.setText(_translate("DialogCAlphaFlexibleFitting", "Alignment", None))
        item = self.tableWidgetCorrespondences.horizontalHeaderItem(0)
        item.setText(_translate("DialogCAlphaFlexibleFitting", "Cluster", None))
        item = self.tableWidgetCorrespondences.horizontalHeaderItem(1)
        item.setText(_translate("DialogCAlphaFlexibleFitting", "CAlpha Helix #", None))
        item = self.tableWidgetCorrespondences.horizontalHeaderItem(2)
        item.setText(_translate("DialogCAlphaFlexibleFitting", "Volume Helix #", None))
        item = self.tableWidgetCorrespondences.horizontalHeaderItem(3)
        item.setText(_translate("DialogCAlphaFlexibleFitting", "Direction", None))
        self.formAlignToCluster.setTitle(_translate("DialogCAlphaFlexibleFitting", "Align to Cluster", None))
        self.labelCluster.setText(_translate("DialogCAlphaFlexibleFitting", "Cluster", None))
        self.pushButtonCorrespondencesAlignToCluster.setText(_translate("DialogCAlphaFlexibleFitting", "Align", None))
        self.formMergeClusters.setTitle(_translate("DialogCAlphaFlexibleFitting", "Merge Clusters", None))
        self.labelFirstCluster.setText(_translate("DialogCAlphaFlexibleFitting", "First Cluster", None))
        self.labelSecondCluster.setText(_translate("DialogCAlphaFlexibleFitting", "Second Cluster", None))
        self.pushButtonCorrespondencesMerge.setText(_translate("DialogCAlphaFlexibleFitting", "Merge", None))
        self.formManualCorresponence.setTitle(_translate("DialogCAlphaFlexibleFitting", "Manual Correspondence", None))
        self.labelMatch.setText(_translate("DialogCAlphaFlexibleFitting", "Correspond currently selected CAlpha and Volume helices to create a new cluster.", None))
        self.pushButtonCorrespondencesManualCorrespondence.setText(_translate("DialogCAlphaFlexibleFitting", "Correspond", None))
        self.formFlipCorrespondenceDirection.setTitle(_translate("DialogCAlphaFlexibleFitting", "Flip Corresponence Direction", None))
        self.labelFlipCorrespondenceDirection.setText(_translate("DialogCAlphaFlexibleFitting", "Flip direction of currently selected Volume and CAlpha helix correspondence.", None))
        self.pushButtonCorrespondencesFlipCorrespondence.setText(_translate("DialogCAlphaFlexibleFitting", "Flip", None))
        self.labelConfirmCorrespondences.setText(_translate("DialogCAlphaFlexibleFitting", "Confirm Correspondences", None))
        self.pushButtonCorrespondencesPreview.setText(_translate("DialogCAlphaFlexibleFitting", "Preview", None))
        self.pushButtonCorrespondencesReject.setText(_translate("DialogCAlphaFlexibleFitting", "Reject", None))
        self.pushButtonCorrespondencesAccept.setText(_translate("DialogCAlphaFlexibleFitting", "Accept", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCorrespondences), _translate("DialogCAlphaFlexibleFitting", "Correspondences", None))
        self.groupBoxRigidFitting.setTitle(_translate("DialogCAlphaFlexibleFitting", "Rigid Fitting", None))
        self.pushButtonDeformationRigidDeform.setText(_translate("DialogCAlphaFlexibleFitting", "Rigid Deform", None))
        self.groupBoxDeformationRigidGlobalOptions.setTitle(_translate("DialogCAlphaFlexibleFitting", "Global Options", None))
        self.labelDeformationRigidFittingMatch.setText(_translate("DialogCAlphaFlexibleFitting", "Match", None))
        self.comboBoxDeformationRigidFittingMethod.setItemText(0, _translate("DialogCAlphaFlexibleFitting", "Alignment", None))
        self.comboBoxDeformationRigidFittingMethod.setItemText(1, _translate("DialogCAlphaFlexibleFitting", "Largest Cluster", None))
        self.comboBoxDeformationRigidFittingMethod.setItemText(2, _translate("DialogCAlphaFlexibleFitting", "Principal Components", None))
        self.groupBoxRigidDeformationPrincipalComponentMatching.setTitle(_translate("DialogCAlphaFlexibleFitting", "Principal Component Matching Options", None))
        self.labelDeformationRigidPrincipalComponentOrientation.setText(_translate("DialogCAlphaFlexibleFitting", "Orientation", None))
        self.comboBoxRigidDeformationPrincipalComponentOrientation.setItemText(0, _translate("DialogCAlphaFlexibleFitting", "Automatic", None))
        self.comboBoxRigidDeformationPrincipalComponentOrientation.setItemText(1, _translate("DialogCAlphaFlexibleFitting", "1", None))
        self.comboBoxRigidDeformationPrincipalComponentOrientation.setItemText(2, _translate("DialogCAlphaFlexibleFitting", "2", None))
        self.comboBoxRigidDeformationPrincipalComponentOrientation.setItemText(3, _translate("DialogCAlphaFlexibleFitting", "3", None))
        self.comboBoxRigidDeformationPrincipalComponentOrientation.setItemText(4, _translate("DialogCAlphaFlexibleFitting", "4", None))
        self.labelDeformationPrincipalComponentTarget.setText(_translate("DialogCAlphaFlexibleFitting", "Target", None))
        self.pushButtonRigidDeformationPrincipalComponentTarget.setText(_translate("DialogCAlphaFlexibleFitting", "Load CAlpha Atoms", None))
        self.groupBoxFlexibleFitting.setTitle(_translate("DialogCAlphaFlexibleFitting", "Flexible Fitting", None))
        self.groupBoxFlexibleDeformationGlobalOptions.setTitle(_translate("DialogCAlphaFlexibleFitting", "Global Options", None))
        self.labelLaplacianNeighborhoodSize.setText(_translate("DialogCAlphaFlexibleFitting", "Laplacian Neighborhood Size", None))
        self.labelTransformation.setText(_translate("DialogCAlphaFlexibleFitting", "Transformation Neighborhood Size", None))
        self.groupBoxFlexibleDeformationSkeletonFitting.setTitle(_translate("DialogCAlphaFlexibleFitting", "Skeleton Fitting Options", None))
        self.labelSkeletonFittingIterations.setText(_translate("DialogCAlphaFlexibleFitting", "Fitting Iterations", None))
        self.labelDistanceTreshold.setText(_translate("DialogCAlphaFlexibleFitting", "Distance Threshold", None))
        self.spinBoxSkeletonFittingDistanceThreshold.setSuffix(_translate("DialogCAlphaFlexibleFitting", " Å", None))
        self.labelSkeletonFittingWeight.setText(_translate("DialogCAlphaFlexibleFitting", "Fitting Weight", None))
        self.labelSkeletonDistortionWeight.setText(_translate("DialogCAlphaFlexibleFitting", "Distortion Weight", None))
        self.pushButtonDeformationFlexibleDeform.setText(_translate("DialogCAlphaFlexibleFitting", "Flexible Deform", None))
        self.groupBoxFlexibleDeformationCorrespondenceFitting.setTitle(_translate("DialogCAlphaFlexibleFitting", "Correspondence Fitting Options", None))
        self.labelBoundingBoxRatio.setText(_translate("DialogCAlphaFlexibleFitting", "BoudingBoxRatio", None))
        self.doubleSpinBoxBoudingBoxRatio.setSuffix(_translate("DialogCAlphaFlexibleFitting", " ", None))
        self.checkBoxRigidInitialization.setText(_translate("DialogCAlphaFlexibleFitting", "Rigid Initialization", None))
        self.checkBoxWSVD.setText(_translate("DialogCAlphaFlexibleFitting", "WSVD", None))
        self.checkBoxAutoStop.setText(_translate("DialogCAlphaFlexibleFitting", "AutoStop", None))
        self.label.setText(_translate("DialogCAlphaFlexibleFitting", "StopThreshold", None))
        self.doubleSpinBoxStopThreshold.setSuffix(_translate("DialogCAlphaFlexibleFitting", " Å", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDeformationOptions), _translate("DialogCAlphaFlexibleFitting", "Deformation Options", None))
        self.labelConfirmDeformation.setText(_translate("DialogCAlphaFlexibleFitting", "Confirm Deformation", None))
        self.pushButtonDeformationReject.setText(_translate("DialogCAlphaFlexibleFitting", "Reject", None))
        self.pushButtonDeformationAccept.setText(_translate("DialogCAlphaFlexibleFitting", "Accept", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDeformation), _translate("DialogCAlphaFlexibleFitting", "Deformation", None))

